#! /usr/bin/env zsh
set -e # exit entire script when command exits with non-zero status

yarn install
expo publish --release-channel production --non-interactive

# Start building standalone android build using `production` release channel
expo build:ios --release-channel production --non-interactive --no-publish

# Download the artifact to current directory as `app.ipa`
curl -o app.ipa "$(expo url:ipa --non-interactive)"

# Use fastlane to upload your current standalone iOS build to test flight on iTunes Connect.
fastlane deliver --verbose --ipa "app.ipa" --skip_screenshots --skip_metadata